### ISSUE TITLE
Larger file size of .splat files

### ISSUE THREAD

**Issue by Bishadkoju** [mkkellogg/GaussianSplats3D#1]
Hi,
I was wondering why the file size of .splat files are so high (100+mb) compared to Kevin's  .splat files(25mb). 
Skimming through the codebase, this implementation also discards the spherical harmonics coefficient. Is there any specific reason for the larger file size ? 
Thank you ! :)

**Comment by mkkellogg** [comment]
My splat files save the splat rotation components as 32-bit floats rather than 8-bit integers, so my splat files are indeed larger (I still plan on making that more efficient). However when you mention 25mb vs 100mb+, I think you might be comparing different files? Also keep in mind that for a lot of these scenes there are 2 different versions, one generated from a lower detail point cloud and one generated from a higher detail point cloud (`iteration_7000` and `iteration_30000` in the data set from the original paper respectively). As an example, my high detail version of `garden.splat` is 245mb whereas Kevin's high detail version is 186mb.

**Comment by hybridherbst** [comment]
Would be awesome if the optimized formats from Aras could work - the tooling already exists and allows a ~5-20x compression rate. 
(Link: https://aras-p.info/blog/2023/09/27/Making-Gaussian-Splats-more-smaller/)

**Comment by mkkellogg** [comment]
@Bishadkoju If you're still interested, you can follow our discussions about a new universal `.splat` format here: [https://github.com/mkkellogg/GaussianSplats3D/issues/47](https://github.com/mkkellogg/GaussianSplats3D/issues/47)

**Comment by Bishadkoju** [comment]
@mkkellogg  yes i am following it. Thank you .
