### ISSUE TITLE
Textured Material not rendering

### ISSUE THREAD

**Issue by Bishadkoju** [mkkellogg/GaussianSplats3D#100]
Hi, I'm trying to augment a textured object in the splat. However, those textured objects are not rendered. How can this be fixed? Also, in the readme file, you mentioned that integrating transparent objects does not work and would be challenging. Could give me the general directions on making this work?

**Comment by mkkellogg** [comment]
What kind of material are you using for the textured object? If it's a material that requires lights, you will need to add lights to the scene. Alternatively you could use something like`THREE.MeshBasicMaterial`, which supports textures and would work without lights.

**Comment by Bishadkoju** [comment]
Thanks that worked. I'm curious how we can render transparent or semi transparent objects in the scene

**Comment by mkkellogg** [comment]
Transparent objects are difficult because the splat scenes themselves are made up of a transparent mesh. Since transparent objects are typically rendered without writing to the depth buffer, other three.js objects and the splat scene won't properly occlude each other. You would need to somehow modify the rendering of the splat scenes to include rendering to the depth buffer. I have actually experimented with that, but the results did not look great.

**Comment by mkkellogg** [comment]
One way that might work for your case, depending on how your transparent objects are positioned relative to each other, is to alter the material for each to write to the depth buffer and set the `.renderOrder` for each to reflect the order in which you want them to be rendered (which will depend on the camera's position and orientation). Then set the `.renderOrder` for the viewer's `.splatMesh` to be larger than any of your other transparent objects, which will cause it to be rendered last. It's not a perfect solution, but it will work for certain cases.

**Comment by mkkellogg** [comment]
I'm going to close this one for now, let me know if you have any further thoughts or questions about this.
