### ISSUE TITLE
Question: Factor 0.45 in focal calculation

### ISSUE THREAD

**Issue by xiasun** [mkkellogg/GaussianSplats3D#108]
Hello, I noticed there's a factor 0.45 on calculating focal length

```
// Viewer.js
updateSplatMesh = function() {

    const renderDimensions = new THREE.Vector2();

    return function() {
        if (!this.splatMesh) return;
        const splatCount = this.splatMesh.getSplatCount();
        if (splatCount > 0) {
            this.splatMesh.updateTransforms();
            this.getRenderDimensions(renderDimensions);
            this.cameraFocalLengthX = this.camera.projectionMatrix.elements[0] *
                                      this.devicePixelRatio * renderDimensions.x * 0.45; // ------ here 0.45
                                      this.cameraFocalLengthY = this.camera.projectionMatrix.elements[5] *
                                      this.devicePixelRatio * renderDimensions.y * 0.45;
            this.splatMesh.updateUniforms(renderDimensions, this.cameraFocalLengthX, this.cameraFocalLengthY);
        }
    };

}();
```

I am wondering what does this factor stands for?
And why not using something like `0.5 * height / tan(0.5 * fov)` to calculate focalLength?

Many thanks!

**Comment by mkkellogg** [comment]
Really the `0.45` should be `0.5` here, I just adjusted it to `0.45` at some point during debugging & experimenting and never changed it back because I thought it looked it good :)

Your formula `0.5 * width / tan(0.5 * fov)` (altered to use width instead of height) is actually equivalent to my formula if I change `0.45` to `0.5` 

`this.camera.projectionMatrix.elements[0]` is equivalent to `(2 * n) / (r - l)` where `n` is the focal length (distance to the near plane). When that is multiplied by `0.5` and then by `renderDimensions.x` (which is the viewport width) you get `(n * width) / (r - l)`. Since `r - l` equals `width`, you're left with `n`, which is the focal length.

The calculation for `cameraFocalLengthY` should yield the same result, so really I should just be passing a single value for focal length to the `updateUniforms()` function.

**Comment by xiasun** [comment]
got it! thanks
