### ISSUE TITLE
Feature: Progressive loading

### ISSUE THREAD

**Issue by AIBluefisher** [mkkellogg/GaussianSplats3D#113]
Hi, @mkkellogg 

Will the project support progressive loading in the future? Also, can the project support more user-friendly interactions such as pressing the forward/backward keys to move forward and backward scenes?

**Comment by mkkellogg** [comment]
I would love to support progressive loading at some point, I think it's a nicer user experience and a pretty cool loading effect. It will take some work because of the way I currently use a `SplatTree` to  organize splats to boost performance -- basically I can't build the `SplatTree` until all the splats are loaded. I have some ideas to address that, I just haven't had time to implement them. Eventually I will :)

As for keyboard controls, that will be much easier to add; I should be able to get those into an upcoming release.

**Comment by sxxov** [comment]
+1 for progressive loading, please!

It's a big blocker for using this library for anything in prod, since making the user wait for a double-digit MiB file to finish downloading before presenting anything is really tough.

**Comment by gotoeasy** [comment]
Hi, has there been any progress regarding this ? Thank you.

**Comment by mkkellogg** [comment]
Progress has been slow, but I have made some. I have a work-in-progress branch `progressive_loading`: https://github.com/mkkellogg/GaussianSplats3D/tree/progressive_loading that has everything I've done so far. Currently I'm only supporting progressive loading for my own `.ksplat` files for a couple of reasons:
- I need to know how many splats are in the file ahead of time so I can allocate resources properly. `.splat` files don't have that info, but `.ply` files do so they could potentially be streamed as part of a future update. I know the `Content-Length` header could be used to determine the number of splats for a `.splat`, but that header is not guaranteed to be present for all web servers. That will also be a future update thing :)
- I wanted to be able to control the layout of the splats in the file, because that has an impact on the kind of effects you can use to unveil the splats (right now I'm organizing them from the center of the scene going outward).

**Comment by mkkellogg** [comment]
@gotoeasy I updated the `progressive_loading`  branch so that `.splat` files can be streamed now. It's still very much a work in progress, but you can try that branch out to preview it.

**Comment by gotoeasy** [comment]
> @gotoeasy I updated the `progressive_loading` branch so that `.splat` files can be streamed now. It's still very much a work in progress, but you can try that branch out to preview it.

Would you consider a transition effect where downloading and rendering happen simultaneously? 
Like in `https://github.com/antimatter15/splat`

**Comment by mkkellogg** [comment]
I'm not sure I understand, isn't that exactly what my `progressive_loading` branch is doing? You should be able to see the scene rendering long before the download is complete and you should see the splats updating in real-time.

**Comment by gotoeasy** [comment]
> I'm not sure I understand, isn't that exactly what my `progressive_loading` branch is doing? You should be able to see the scene rendering long before the download is complete and you should see the splats updating in real-time.

I saw the transition effect after pulling the new code. great!!!

**Comment by mkkellogg** [comment]
Great! Let me know if you have any questions or other feedback. I hope to merge these updates into the main branch soon.

**Comment by gotoeasy** [comment]
> Great! Let me know if you have any questions or other feedback. I hope to merge these updates into the main branch soon.

I tried multiple models for viewing, and the results seemed quite good.

However, during the "Processing splats..." phase, it seems like the CPU usage is very high, causing short periods of lag. Nevertheless, this is not the same issue.

**Comment by gotoeasy** [comment]
Apart from the default transition effect, it might be worth considering multiple built-in effect options for developers to choose from during development.

Transition effects like Luma also give a nice feel (similar to how supersplat adjusts the splat size).

![image](https://github.com/mkkellogg/GaussianSplats3D/assets/9602197/b59a05f5-55ac-48d1-9743-f72bbe353e45)
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/9602197/355623ae-c4f3-495e-83c6-c987bda82a6e)
![image](https://github.com/mkkellogg/GaussianSplats3D/assets/9602197/2560e2f4-caeb-4604-a07d-8475773af3b9)

**Comment by mkkellogg** [comment]
Definitely worth considering, although to some extent the kinds of transitions possible depend on how the splats are organized in the file and the order in which they are downloaded. I'll work on adding more effects in a later release :)

**Comment by mkkellogg** [comment]
For what it's worth, I updated the `.ksplat` format and the exporter for it to organize the splats going from a scene's center outward. The result is kind of similar to Luma's approach for unveiling the scene from the center outwards, although I don't shrink the splats at point during the transition.

**Comment by seppestaes** [comment]
Amazing work! Are there any limits in this progressive_loading branch on the compressionLevel? Thx!

**Comment by gotoeasy** [comment]
> Great! Let me know if you have any questions or other feedback. I hope to merge these updates into the main branch soon.

When `streamView` is set to true, calling the `viewer.dispose()` method can easily lead to exceptions, especially when the model file has not fully loaded and displayed. After several repeated openings and closings, increased memory, CPU, or GPU usage may occur, potentially resulting in newly opened models failing to display.

**Comment by mkkellogg** [comment]
Ah, that's a great point. I'll have think a bit about how to best handle that. Hopefully it's as simple as cancelling the download as part of the call to `dispose()`.

**Comment by mkkellogg** [comment]
I've made some updates to hopefully address the most recent issues with disposing while in the middle of loading. The exceptions you were seeing should now be prevented, and there was a memory leak that I fixed as well. Take a look when you have some time!

**Comment by gotoeasy** [comment]
It's ok now. Great!

**Comment by gotoeasy** [comment]
Can the `Viewer.addSplatScenes` method add this feature?

**Comment by mkkellogg** [comment]
Eventually I would like to support streaming multiple scenes simultaneously, but for this upcoming release it will just be for single scenes.

**Comment by gotoeasy** [comment]
During the transition effect, the parameter `splatAlphaRemovalThreshold` is not functioning.
Testing with `splatAlphaRemovalThreshold = 250` clearly demonstrates this.

**Comment by mkkellogg** [comment]
Yeah I noticed this issue too. I have a fix in the [progressive_loading_updates](https://github.com/mkkellogg/GaussianSplats3D/tree/progressive_loading_updates) branch, can you see if that works for you?

**Comment by mkkellogg** [comment]
Going to close this for now, At some point in the future I hope to add support for progressively loading multiple scenes.
