### ISSUE TITLE
Feature: Extend to 4D Setting

### ISSUE THREAD

**Issue by zcmcxm** [mkkellogg/GaussianSplats3D#115]
Hi! Thanks for the great work! :)

I am interested in utilizing the viewer for a 4D (3D + time) setting, specifically to display a series of 3D GS models periodically. My idea to do so will be to keep changing the 3DGS model after every short period (e.g. remove the 3DGS model of timestamp t and add the model of timestamp t+1).
[The demo code of MAV3D](https://github.com/Make-A-Video3D/Make-A-Video3D.github.io/blob/8767f6db4592c54ddb7bcea7296bf21ddb61ad4e/render_draco.html#L132) will be a good illustration of what I want to achieve.

I am very new to interactive computer graphics so I wonder if I can do this with your current work. I appreciate it if you could give me some insights or guidance. Thanks! :)

**Comment by mkkellogg** [comment]
My viewer is probably not a good fit for what you're describing, at least in its current state. You can load multiple GS scenes simultaneously, but there's currently no way to individually toggle their visibility, since they're all aggregated into a single Three.js mesh. Maybe someday I'll work on that :)

**Comment by mkkellogg** [comment]
I'm going to close this issue because I already have another one similar to it open: https://github.com/mkkellogg/GaussianSplats3D/issues/102.  I think long-term, 4D support is definitely something I'd like to add.
