### ISSUE TITLE
Initial camera pose not properly configured in WebXR

### ISSUE THREAD

**Issue by wing-kit** [mkkellogg/GaussianSplats3D#136]
After pressing the "START AR" button. The camera position changed to (0,0,0).

Can it preserve the camera pose?

**Comment by mkkellogg** [comment]
Can you post the code you are using to set up the viewer? That might help me troubleshoot.

**Comment by mkkellogg** [comment]
For what it's worth I've found that it's much better to not try to set the  initial camera position and let the WebXRManager in three.js manage that instead. This is because the web xr manager knows where the headset is relative to the web xr frame, so forcing its position to be something else causes problems.

**Comment by mkkellogg** [comment]
One thing you could actually do right now is set the position of the scene when you load it (or the position or scale for that matter) to achieve a similar effect to translating the gaussians:

```
viewer.addSplatScene(path, {
    'position': [1, 2, 3]
})
.then(() => {
    viewer.start();
});
```
