### ISSUE TITLE
error build

### ISSUE THREAD

**Issue by jaccen** [mkkellogg/GaussianSplats3D#15]
npm run build

> gaussian-splat-3d@1.0.0 build
> npm run build-library && npm run build-demo

> gaussian-splat-3d@1.0.0 build-library
> npx rollup -c && mkdir -p ./build/demo/lib && cp ./build/gaussian-splat-3d* ./build/demo/lib/

./src/index.js → ./build/gaussian-splat-3d.umd.cjs...
(!) Broken sourcemap
https://rollupjs.org/troubleshooting/#warning-sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as "base64") should generate accompanying sourcemaps.
created ./build/gaussian-splat-3d.umd.cjs in 131ms

./src/index.js → ./build/gaussian-splat-3d.module.js...
(!) Broken sourcemap
https://rollupjs.org/troubleshooting/#warning-sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as "base64") should generate accompanying sourcemaps.
created ./build/gaussian-splat-3d.module.js in 70ms
命令语法不正确。

**Comment by mkkellogg** [comment]
The build technically is not broken, you're just seeing warnings due to the `rollup-base-64` plugin not correctly indicating to `rollup` that it does not produce source maps. I've added my own custom version of that plugin to do the importing that does tell `rollup` that it does not produce source maps and the warning went away.
