### ISSUE TITLE
Basic Usage stuck on Processing Splat

### ISSUE THREAD

**Issue by tansh-kwa** [mkkellogg/GaussianSplats3D#159]
I'm trying to get the Basic Usage snippet to render a gaussian splat I've captured. I have verified that the online demo, as well as a local instance of the demo can both properly load and visualize the splat very quickly (under a few seconds till the splat is rendered). However, when I try to load the same file using the code included under [`Basic Usage`](https://github.com/mkkellogg/GaussianSplats3D?tab=readme-ov-file#basic-usage) the webpage keeps displaying the loading animation, reading 'Processing splats.' 

I am using `npx vite` to build and serve my code & loading this package via npm. I've seen some references to this potentially being a CORS issue, however I'm not sure how I can verify that, I've tried changing the --cors  flag with vite but it does not change anything.

Any help is much appreciated.

**Comment by mkkellogg** [comment]
Could you check the debug console to see if there are any errors or messages there that might clue us in to what is happening?

**Comment by mkkellogg** [comment]
Since you're using Vite, I don't have a lot of good recommendations for you. Could you try modifying one of the demo pages that you know works by pasting the basic usage example into it and see if it still works after that? FWIW I just did that on my end and everything seems to work. If it's a Vite related issue, maybe this thread will help: https://github.com/mkkellogg/GaussianSplats3D/issues/41
