### ISSUE TITLE
Compatibility between Viewer & PostProcessing Effects

### ISSUE THREAD

**Issue by tansh-kwa** [mkkellogg/GaussianSplats3D#178]
Does the viewer currently support postprocessing effects in threejs. I've added elements to the scene that I would like to post-process with the Composer object. This contains a reference to the renderer, however, passing the Composer directly to the dropInViewer causes issues the errors. Calling .render() on the composer in the update function causes the splat to disappear. 

I suppose I want to ask if there is anything to look out for w.r.t compatibility with threejs post processing.

**Comment by mkkellogg** [comment]
You definitely have to be careful with post-processing effects, especially when they depend on depth buffer data; they're not a one-size-fits-all solution. The issue with combining splats and post-processing results is that the splats are always rendered as transparent objects (no depth-buffer data) and if the results of the post-processing are also transparent, then there will be no way to guarantee proper rendering order (because of the lack of depth buffer data). Often there can be workarounds, but they will be very specific to the effect you are trying to achieve. Would you be able to share your code? Maybe I can figure out a quick solution.

**Comment by mkkellogg** [comment]
So I think I may understand what's happening. When you don't have the FXAA pass it's pretty straightforward -- the outline effect gets rendered first, but since there's no depth data associated with it (since it's transparent), the splats get rendered over it (because they get rendered second). The  non-transparent scene objects (the yellow spheres) are still visible because they have depth data associated with them and the splat renderer performs a depth test during rendering.

For the case when you have FXAA enabled, my guess is that the result of the FXAA render pass is stored in `renderTarget` , since `renderToScreen` is not set for that pass. However the splat renderer doesn't know about any of that it just renders the splats to the default render buffer.

Is this all your code? How does `renderTarget` ultimately get displayed?

**Comment by mkkellogg** [comment]
Well I'm just guessing, but I think the output of the FXAA pass will be rendered to `renderTarget` and not the screen, because it is designated as the output render target for the composer:
```
const composer = new EffectComposer(viewer.renderer, renderTarget);
```

Whereas the output of the outline pass gets rendered to the screen because of this line:
```
outlinePass.renderToScreen = true;
```
So I was just wondering how you actually see the output of the FXAA pass? (Disclaimer: I am not very familiar with how the effect composer works; I have never used it myself).

**Comment by mkkellogg** [comment]
It definitely makes sense that when you render the composer after the viewer renders, the splat is gone. I assume the composer clears the render buffer before performing its own rendering. Could you turn off the `autoClear` property of the renderer before the composer renders and restore after? Maybe something like:
```
renderer.clear(true, true, true);
viewer.update();
viewer.render();
renderer.autoClear = false;
composer.render();
renderer.autoClear = true;

```

I added the `renderer.clear(true, true, true);` line because the viewer disables the auto clear before it renders, and restores it after.

**Comment by mkkellogg** [comment]
So I've discovered a couple of things. Three.js' `EffectComposer` is meant to be used for all rendering, so you shouldn't be trying to call `viewer.render()` and then following that up with `composer.render()`. What really needs to be done is figure out a nice way to make rendering a splat one of the composer's passes, so you could just called `composer.render()` and it would render everything... that will take a bit of work :)

As for why adding the FXAA pass makes the splats go away, it looks like that pass writes to the depth buffer (which doesn't make sense to me) and then when the viewer renders the splats, none of it is visible because according to the depth buffer it should all be occluded. I found that adding the line `effectFXAA.material.depthWrite = false;` makes the splats visible.

However this doesn't really solve the issue of how to properly use the effect composer with the splat viewer. I don't think there is a good way to do that right now, I'm going to have to spend some time working on that.

**Comment by mkkellogg** [comment]
Just make sure your code to add passes looks like:
```
    const composer = new EffectComposer(renderer, renderTarget);
    const pass = new RenderPass(threeScene, camera);
    composer.addPass(pass);
    composer.addPass(outlinePass);
    composer.addPass(effectFXAA);
    effectFXAA.material.depthWrite = false;
```
The last line is the important one. Then make sure you're calling `composer.render()` before `viewer.render()`. As for calling `composer.render()` after `viewer.render()`, that just won't work because the composer is clearing the screen. Again this is not a real solution, a real solution will require more work :)

**Comment by mkkellogg** [comment]
Awesome, that's really good to know!

**Comment by mkkellogg** [comment]
I'm going to close this for now, but I think I might eventually add something to the README about doing stuff like this. Thanks again for digging into this!
