### ISSUE TITLE
LAN IP like(192.168.) cannot load the demo page

### ISSUE THREAD

**Issue by yang1hu** [mkkellogg/GaussianSplats3D#205]
Hi,this is a great project ! there is a problem when i run the demo from source code. i am a newer to node. i found  when a use 127.0.0.1 can visit the page .however ,cannot visit from 192.168., i found there is a js file cannot load successfully,  just this function createSplatTreeWorker

**Comment by mkkellogg** [comment]
To access the demo at an address like `192.168.*.*` you'll need to set up something a little more sophisticated than what I have for the local demo because you need to enable SSL. What I have done for my local network is use an NPM package called [local-ssl-proxy](https://www.npmjs.com/package/local-ssl-proxy) to run an SSL enabled proxy server that redirects to my local demo.  So for example, if you have my demo running at `192.168.1.10:8080` you could  run the proxy like this:
```
npx local-ssl-proxy -s 9001 -t 8080
```

Then you could access the URL `192.168.1.10:9001` and it would redirect to my demo, but with SSL enabled.

**Comment by mkkellogg** [comment]
No problem! Just to clarify -- this is now working for you?

**Comment by mkkellogg** [comment]
I'm going to close this for now, let me know if you run into any more problems.
