### ISSUE TITLE
Are there currently any APIs provided to obtain this signal when artifacts disappear?

### ISSUE THREAD

**Issue by lucylucy27** [mkkellogg/GaussianSplats3D#255]
Hi, 
I'm curious, is the sortWorker.done message the latest information that the CPU or the user can capture related to rendering readiness? Is the signal of the disappearance of artifacts determined internally by the GPU rendering pipeline? If yes, are there currently any APIs provided to obtain this signal?
Thanks!

**Comment by mkkellogg** [comment]
I'm not sure what you mean by "the disappearance of artifacts".  When the sort worker receives the `sortDone` message, that means the the scene is ready for rendering from whatever position the user was at when the sort started. If you really need to execute a function when the sort completes, you can add a callback to the `Viewer.runAfterNextSort` array (it's not super elegant because I never meant for that t be used externally).
