### ISSUE TITLE
Loading animation like in Luma WebGL Library

### ISSUE THREAD

**Issue by AlexRynas** [mkkellogg/GaussianSplats3D#288]
Are there any plans to implement scene loading like in the Luma WebGL Library?
https://lumalabs.ai/luma-web-library

**Comment by mkkellogg** [comment]
At some point I would like to implement something like that, and allow developers to customize the effect to some extent. One thing you can do now is export your scene to a `.ksplat` file and load it progressively. The data in `.ksplat` files is organized so that it can be revealed from the center outward as it is downloaded.

If you are working with the source code and not with the `npm` package, you can make the values of these variables smaller: https://github.com/mkkellogg/GaussianSplats3D/blob/ef524f4308c7793c78005aeedc03a2f8f8f138fa/src/splatmesh/SplatMesh.js#L30 If you do that, you won't necessarily need to load your scene progressively.

**Comment by MarcelloPajntar97** [comment]
sorry @mkkellogg any update about that? im trying to progressively load splat but the effect is very snappy

**Comment by mkkellogg** [comment]
Sorry for the late response, there's still currently no way to adjust the fade-in speed other than through the method described above. I'll try to add something to the next release.

**Comment by mkkellogg** [comment]
If you want to try the [memory-optimizations](https://github.com/mkkellogg/GaussianSplats3D/tree/memory-optimizations) branch, you can specify a value for the `Viewer` parameter `sceneFadeInRateMultiplier`. Any value greater than 1.0 will speed up the scene reveal and a value between 0.0 and 1.0 will slow it down.

**Comment by mkkellogg** [comment]
The `sceneFadeInRateMultiplier` parameter for `Viewer` is now in the latest release [(v0.4.5)](https://github.com/mkkellogg/GaussianSplats3D/releases/tag/v0.4.5) if you want to try it out. I'll close this for now, but let me know if you have further questions.
