### ISSUE TITLE
Processing splats Hung

### ISSUE THREAD

**Issue by LaFeuilleMorte** [mkkellogg/GaussianSplats3D#291]
I was trying to render splats from my local folder. But the scene cannot be displayed and the webpage stuck in processing splats. Here's the error message from the console.
<img width="566" alt="image" src="https://github.com/user-attachments/assets/95a783c1-cbfe-4d2e-95c3-5d19ba2a9084">

**Comment by mkkellogg** [comment]
You're experiencing a common CORS-related issue here. Read through the CORS section of the documentation, that might have the answer to your specific problem: https://github.com/mkkellogg/GaussianSplats3D?tab=readme-ov-file#cors-issues-and-sharedarraybuffer

**Comment by LaFeuilleMorte** [comment]
> You're experiencing a common CORS-related issue here. Read through the CORS section of the documentation, that might have the answer to your specific problem: https://github.com/mkkellogg/GaussianSplats3D?tab=readme-ov-file#cors-issues-and-sharedarraybuffer

I read the doc. And I see these two lines are already added here. So The problem might be using the "http" rather than "https"? How can I redirecting http in https in util/service.js?
![image](https://github.com/user-attachments/assets/88aef39e-3bb9-453d-836c-bee6cca2d9c4)

**Comment by mkkellogg** [comment]
Are you just trying to access the demo page? Are you trying to access it locally or from another machine? If you are accessing it from a different machine, you will probably need to access it via `https`, in which case `util/server.js` won't work by itself. I myself have set up an SSL proxy on the machine running my demo page so that I can access it from a different machine. I admit it's not a great setup, but `util/server.js` was never meant to be a real web server.

**Comment by mkkellogg** [comment]
I'll close this for now, please let me know if you need more assistance.
