### ISSUE TITLE
How to know whether all Gaussians that should be visible in the camera's view frustum are indeed loaded?

### ISSUE THREAD

**Issue by Justus03** [mkkellogg/GaussianSplats3D#318]
Thanks for your work!

I'm trying to render png images of my 3dgs scene but whenever I do I get incomplete images with some black zones. I'm using a laptop with no gpu so it takes some times for gaussians to load and render.

**Comment by v2img** [comment]
Does this work? inside src/viewer.js'
`isLoadingOrUnloading() {
        return Object.keys(this.splatSceneDownloadPromises).length > 0 || this.splatSceneDownloadAndBuildPromise !== null ||
                           this.splatSceneRemovalPromise !== null;
    }`

**Comment by mkkellogg** [comment]
I can't think of a way to know if all gaussians that should be visible are loaded before loading them because you'd need their position information to do that kind of test, unfortunately. If you turn off progressive loading, you can just wait until the entire model loads to be sure you're seeing everything there is to see.
