### ISSUE TITLE
How to get the splats' depth info for current frame

### ISSUE THREAD

**Issue by lucylucy27** [mkkellogg/GaussianSplats3D#328]
Hi Mkkellogg,

I want to get the splats' depth info when rendering. But it seems difficult for me.
Can you give some hint of how to achive the depth texture by CPU side?

Thanks for your great work~

**Comment by lucylucy27** [comment]
vertexShaderSource += `
                vec4 viewCenter = transformModelViewMatrix * vec4(splatCenter, 1.0);
                **vPosition.z = viewCenter.z;**
               ...
            `;
Is this value **viewCenter.z** the depth of splats?

**Comment by mkkellogg** [comment]
Not quite. The actual depth value for a splat is calculated at this line: https://github.com/mkkellogg/GaussianSplats3D/blob/2d80511077fcb83ec5cb6da7336dc38e55d4a14b/src/splatmesh/SplatMaterial.js#L166
And `ndcCenter.z` is the actual depth that would be rendered to the depth buffer if the depth buffer weren't disabled.  It's a little tricky though, because the depth of a splat is really only valid for the splat's center, in a mathematical sense. All of the splat will be render with that depth value, but don't expect the result to be clean, coherent surfaces like you would get with a mesh.

**Comment by lucylucy27** [comment]
Thanks for your kind reply :)
I test this value and found it is between (0.8, 1.0) in my scene.
Does this mean we need some **clamp** operation for the depth value?
