### ISSUE TITLE
Rendering mishap

### ISSUE THREAD

**Issue by nkyriazis** [mkkellogg/GaussianSplats3D#339]
The viewer has worked OK in several scenes I've tried.

Lately I run into a problem viewing [this](https://drive.google.com/file/d/1DIDdoWcuZtRgvrraKNJfalJ7DV7O7yrR/view?usp=sharing) scene.

This is what i get in this viewer:
![image](https://github.com/user-attachments/assets/5c9f089a-be15-44e2-9ca7-5c08f80849f9)

This is how it should look like (postshot):
![image](https://github.com/user-attachments/assets/5779f0bb-03ab-40f6-9715-5e8acfe6cd6f)

This is not an approximation error, it seems like unexpected behavior.

I tried toying around with the sorting options and other rendering options, but it always yielded the same issues.

Any ideas?

**Comment by mkkellogg** [comment]
I tried with the following `Viewer` parameters and it seemed to help on my end:

```javascript
const viewer = new GaussianSplats3D.Viewer({
      'integerBasedSort': false,
      'splatSortDistanceMapPrecision': 18,
});
```

I think the key is to make sure `integerBasedSort` is set to false. It makes the viewer use a floating point sort, with is more accurate, but will decrease performance a little. I don't think you necessarily even need to change `splatSortDistanceMapPrecision` from the default (which is 16), I just added that to see if it helps.

**Comment by nkyriazis** [comment]
Right, disabling integer sorting fixed it. It shouldn't have to do with the number of points but with the spatial extents, right? I mean, I've tried significantly larger splats without a problem.

Thank you for looking into it!

**Comment by mkkellogg** [comment]
It's really more about the density of points in the counting sort distance map. You can have spatial extents that are small, but still have a high density. Conversely you have have large extents with low point density. That's why I brought up the `splatSortDistanceMapPrecision` parameter -- it allows for higher precision in the counting sort distance map. The `integerBasedSort` parameter has an impact on the precision of splat placement in the distance map as well, but in a different way.
