### ISSUE TITLE
Rendering 99% of the gaussians despite not looking at their direction

### ISSUE THREAD

**Issue by abrahamezzeddine** [mkkellogg/GaussianSplats3D#361]
Hello,

I am wondering if there is a way to make this more effective? As of now, it seems that the renderer is still rendering the majority of the splats despite not looking at their direction. If I for example look away to the emptiness, I might render around 6% of the splats. 

What are the factors that determine how much is rendered? See image as an example where I am high above the ground and looking at the distant (non-important) splats. Thank you! :)

![image](https://github.com/user-attachments/assets/6b311c77-ac31-4195-bc85-7dd2851ed933)

**Comment by abrahamezzeddine** [comment]
Any idea?

**Comment by mkkellogg** [comment]
The "Rendering" line in the info panel actually refers to the number of splats being sorted for rendering. The reason you're not seeing the expected drop in that number is that the viewer is intentionally selecting a significant number of splats that are outside the view frustum to be sorted. This is so that if the user quick rotates the camera, there won't be a bunch of black space on screen during the time when the sorting algorithm is catching up to the new camera orientation. These splats are also sent to the GPU to be rendered, but the shaders discard them if they are outside the frustum.

**Comment by abrahamezzeddine** [comment]
Thank you!!
