### ISSUE TITLE
[Question] Is there a "common solution" for centring models?

### ISSUE THREAD

**Issue by rowild** [mkkellogg/GaussianSplats3D#44]
My current workflow is:
- Create in Luma / poly.cam
- Download .ply
- Clean up in `Super Splash`
- Convert to `.splat` with GaussianSplats3D
- Upload / implement `.splat`

The issue I encounter is that the orientation of a splat is obviously treated very differently among software. I am aware of the Y/Z-axis, but in this case the splat is not 90 degrees off (which I would expect, when y and z axis were treated differently), but the splat is completely turned around.

The screenshot shows what I have in `Super Splash` and the video here: 
https://dl.rowild.at/GaussianSplats3D_upside_down.mp4
shows what `GaussianSplats3D` is doing with the (converted from `.ply`) `.splat`.

I am aware that the distance of the camera has to be adjusted in most cases. (Of course I would love to know if that is the case, because the `.splat` is scaled differently or is there really just a difference ein placing the camera.) 
But, as mentioned above: the splat is turned upside-down in `GaussianSplats3D` – and that does not really seem to be the case, because the z-axis is defined differently.

Not sure, if my thinking is totally wrong and splats work completely different from meshes, or if there is something else off...
I know my way around three.js so-lala and would like to think that, along with the documentation, I can re-define the OrbitControls and the camera so that my splat is handled properly. But it seems that currently these adjustments have to be done on a splat-to-splat basis.

**Comment by mkkellogg** [comment]
All `.ply` files I have worked with have had unique natural orientations that are all close to being upside-down. That's why I added the `cameraUp` parameter to the `Viewer` constructor, so that the camera's orientation adjusts to the scene's orientation. Super splat seems automatically flip a splat scene upside-down when you load it from a `.ply` file but maybe it doesn't export it that way? I will look into that a bit more. 

In the meantime, you can adjust the camera's up vector using the left or right arrow keys. You can also press `P` to view a debug object that shows the orientation of the camera's orbital plane. That may help you find the camera up vector that works for your scene. For the scene you're testing with, `[0.01525, -0.17658, 0.98417]` seems to work well for the camera up vector.

**Comment by rowild** [comment]
@mkkellogg Your vector suggestion for the camera up setting is perfect, thank you!
