### ISSUE TITLE
Depth sorting for foreign objects

### ISSUE THREAD

**Issue by SergeiK-27** [mkkellogg/GaussianSplats3D#5]
Is it possible to make depth sorting apply to added 3b objects? For example debug meshes in demo are rendered even when occluded by terrain
<img width="766" alt="image" src="https://github.com/mkkellogg/GaussianSplats3D/assets/69177597/0e532339-b8cd-4af5-837a-78904ef063b7">

**Comment by mkkellogg** [comment]
Something like that might technically be possible, but not without a significant amount of effort :) The splats are technically part of a single mesh so they are rendered in a single draw call. They are ordered only relative to each other and not to other objects in the scene.

**Comment by timokorkalainen** [comment]
It seems this Unity viewer can do depth sorting, if helps at all as reference: https://github.com/aras-p/UnityGaussianSplatting

**Comment by mkkellogg** [comment]
In reality you should be able to update the shader for the splat buffer to output proper depth values, something like changing ` gl_Position = vec4(projectedCovariance, 0.0, 1.0);` to ` gl_Position = vec4(projectedCovariance, pos2d.z/pos2d.w, 1.0)` You would also have to update the splat shader to use the Three.js camera projection matrix instead of the custom one it currently uses so that it matches with other objects in the scene.

However there still seems to be an issue preventing this from working and I can't figure it out. It seems that the blending mode mode I'm using for the splat material `THREE.CustomBlending` makes the depth buffer not work at all. When I change it to `THREE.NormalBlending`, then other objects in the scene get occluded by the splat mesh. But then the splat mesh doesn't look right at all.

**Comment by mkkellogg** [comment]
So I realize now that the issue has to do with the specific way the renderer composites the splats: Each time a splat is rendered, each pixel's contribution to the scene is weighted by subtracting the value of the alpha channel in the existing pixel in the color buffer. Since opaque debug objects in my viewer are rendered with an alpha of 1.0, nothing can be rendered over them with that compositing strategy.

**Comment by mkkellogg** [comment]
FWIW I figured out a way to utilize off-screen render targets to allow "normal" three.js objects to be included. I added a new parameter to the `Viewer` class so that you can pass in a custom scene to be rendered:
```javascript
const scene = new THREE.Scene();

const boxColor = 0xBBBBBB;
const boxGeometry = new THREE.BoxGeometry(2, 2, 2);
const boxMesh = new THREE.Mesh(boxGeometry, new THREE.MeshBasicMaterial({'color': boxColor}));
scene.add(boxMesh);
boxMesh.position.set(3, 2, 2);

const viewer = new GaussianSplat3D.Viewer(null, cameraUp, initialCameraPos, initialCameraLookAt, scene);
```
