### ISSUE TITLE
Is it possible to modify the 'splatAlphaRemovalThreshold' parameter during the rendering process?

### ISSUE THREAD

**Issue by Xposeder** [mkkellogg/GaussianSplats3D#79]
This library is very useful and perfectly meets my needs. I would like to implement a loading animation similar to LumaAI based on this. It seems that they may also control the 'splatAlphaRemovalThreshold' parameter to achieve this, as seen here: https://lumalabs.ai/capture/443a844e-525f-41e1-9750-1dff62782466. I roughly examined the code and it seems that the 'splatAlphaRemovalThreshold' parameter is already passed to the 'loadFileToSplatBuffer' function before rendering, and afterwards, it seems that the parameter cannot be modified to adjust the rendering behavior. Therefore, I would like to know if I have missed anything or if there is any way to achieve this, thanks！

**Comment by mkkellogg** [comment]
The `splatAlphaRemovalThreshold` is only used to decide which splats to leave out completely when a loading a file, it's unfortunately not something that you can change dynamically when the app is running. I think the way Luma AI achieves the effect is that they render the splats as they are downloaded and order the splats in the splat file so that they produce what you see in the above example. My app unfortunately doesn't support progressive loading and won't render anything until the entire scene is downloaded (I plan to eventually support progressive loading when I have time). You could still achieve a similar effect once the scene is downloaded by modifying the shader and fading in splats based on their distance from the scene's center. There's currently a PR that shows a similar effect: [https://github.com/mkkellogg/GaussianSplats3D/pull/59](https://github.com/mkkellogg/GaussianSplats3D/pull/59)

**Comment by mkkellogg** [comment]
A quick and easy way to do it would be to just modify the `SplatMesh` shader to clamp any alpha values less than the desired threshold to 0. You wouldn't see the splats, but they would still technically be rendered.

A proper way to do it would be to modify the results of the sort to eliminate splats based on their alpha. You could do that in the sort worker, but you'd have to pass splat alphas to it. Or you could modify the code where the sorted splat indexes are uploaded to the GPU, but it might cause performance issues with rendering.
