### ISSUE TITLE
When zooming out the scene using the mouse, some objects start to disappear at a certain distance.

### ISSUE THREAD

**Issue by pkq111** [mkkellogg/GaussianSplats3D#88]
When using the mouse wheel to zoom in on the scene, some objects disappear partially. I have tried setting the camera's far clipping plane to 2000, but it doesn't seem to have any effect.

**Comment by mkkellogg** [comment]
So this is happening because of a design issue I need to fix. Right now the maximum render distance is hardcoded here: [https://github.com/mkkellogg/GaussianSplats3D/blob/59367d7111688b068d71a02ac8d39f373d28e627/src/Viewer.js#L1040](https://github.com/mkkellogg/GaussianSplats3D/blob/59367d7111688b068d71a02ac8d39f373d28e627/src/Viewer.js#L1040)
I need to make this value configurable.
